spring.application.name=BankManagement
server.port=8080

# PostgreSQL Ba?lant?s?
spring.datasource.url=jdbc:postgresql://localhost:5432/Bank
spring.datasource.username=postgres
spring.datasource.password=011025

# Hibernate & JPA Ayarlar?
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Resim Yükleme Ayarlar?
spring.servlet.multipart.max-file-size=5MB
app.upload.dir=uploads/